'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { User } from '@/lib/auth';
import { loadTossPayments } from '@tosspayments/tosspayments-sdk';
type Membership = { active: boolean; configured: boolean; amount: number; renewsAt?: string; cancelled?: boolean; pending?: boolean; subscribed?: boolean };
import { exampleInvitation, Invitation } from '@/lib/invitations';
import InvitationView, { Botanical } from './invitation-view';
import ImageEditor from './image-editor';
const themes = [{ id: 'linen', name: '클래식 리넨', description: '시간이 지나도 변하지 않는 담백함' }, { id: 'rose', name: '로즈 레터', description: '사랑을 닮은 은은한 로즈빛' }, { id: 'sage', name: '가든 세이지', description: '싱그러운 초록이 건네는 초대' }] as const;
async function api(url: string, method = 'POST', body?: unknown) {
  const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error || '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.'); return data;
}
export default function WeddingStudio({ user, authReady, githubReady, googleReady, initialMembership, initialItems }: { user: User | null; authReady: boolean; githubReady: boolean; googleReady: boolean; initialMembership: Membership; initialItems: Invitation[] }) {
  const router = useRouter();
  const [member, setMember] = useState(initialMembership), [items, setItems] = useState(initialItems), [draft, setDraft] = useState<Invitation | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [selectedTheme, setSelectedTheme] = useState<Invitation['theme']>('linen');
  useEffect(() => { setMember(initialMembership); setItems(initialItems); }, [initialMembership, initialItems]);
  async function refresh() {
    if (!user) return;
    const result = await api('/api/payments/status', 'GET'); setMember(result); return result;
  }
  useEffect(() => {
    const value = new URLSearchParams(window.location.search).get('payment');
    if (value === 'success') { void refresh().then(state => { setMessage(state?.active ? '구독 결제가 확인되었습니다.' : '구독 상태를 확인해 주세요.'); router.refresh(); }).catch(() => setMessage('구독 확인을 다시 시도해 주세요.')); }
    if (value === 'failed') setMessage('결제를 확인하지 못했습니다. 결제 내역을 확인한 뒤 다시 시도해 주세요.');
  }, [user?.id, router]);
  async function perform(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  function create(theme = selectedTheme) {
    if (!user) { setMessage('로그인한 뒤 이용권을 구매하고 청첩장을 만들어 주세요.'); document.querySelector('#membership')?.scrollIntoView({ behavior: 'smooth' }); return; }
    if (!member.active) { setMessage('청첩장 제작 이용권을 구매해 주세요.'); document.querySelector('#membership')?.scrollIntoView({ behavior: 'smooth' }); return; }
    setDraft({ ...exampleInvitation, id: '', ownerId: user.id, firstName: '', secondName: '', date: '', time: '12:00', venue: '', address: '', directions: '', theme });
    setTimeout(() => document.querySelector('#editor')?.scrollIntoView({ behavior: 'smooth' }), 0);
  }
  const login = authReady ? <span className="w-login-options">{githubReady && <a className="w-button" href="/api/auth/github">GitHub 로그인 ↗</a>}{googleReady && <a className="w-button" href="/api/auth/google">Google 로그인 ↗</a>}</span> : <p className="setup-copy">로그인 연결을 준비 중입니다.</p>;
  async function startPayment() {
    const data = await api('/api/payments/checkout');
    if (data.completed) { await refresh(); router.refresh(); setMessage('구독 결제가 확인되었습니다.'); return; }
    const toss = await loadTossPayments(data.clientKey);
    await toss.payment({ customerKey: data.customerKey }).requestBillingAuth({
      method: 'CARD',
      successUrl: new URL('/api/payments/confirm?setupId=' + encodeURIComponent(data.setupId), window.location.origin).href,
      failUrl: new URL('/?payment=failed', window.location.origin).href,
    });
  }
  return <>
    <header className="w-header"><a className="w-brand" href="/">우리의 날<span>OUR DAY</span></a><nav><a href="#designs">디자인</a><a href="#how">제작 안내</a><a href="#membership">멤버십</a>{user && <a href="#my-invitations">내 청첩장</a>}</nav><div className="w-account">{user ? <><span>@{user.login}</span><button disabled={busy} onClick={() => void perform(async () => { await api('/api/auth/logout'); window.location.assign('/'); })}>로그아웃</button></> : login}</div></header>
    <main className="w-main"><section className="w-hero"><div className="w-hero-copy"><span className="w-eyebrow">A LITTLE LETTER, A LIFETIME OF LOVE</span><h1>함께할 모든 날의<br/>첫 번째 <em>초대.</em></h1><p>두 사람의 이야기를 담은 모바일 청첩장.<br/>소중한 이들에게, 가장 우리다운 마음을 전하세요.</p><div className="w-hero-actions"><button className="w-button dark" onClick={() => create()}>우리의 청첩장 만들기 ↗</button><a href="#designs">디자인 둘러보기 ↓</a></div><div className="w-hero-note"><span>01 /</span> 이름과 마음을 담고 <span>02 /</span> 링크 하나로 전하세요</div></div><div className="w-hero-art"><span className="w-art-label">THE BEGINNING OF US</span><div className="w-envelope"/><div className="w-sample"><InvitationView item={exampleInvitation} compact/></div><span className="w-art-caption">오래 기억될 하루를 위한, 작은 편지.</span></div></section>
      {message && <div className="w-notice" role="status"><span>{message}</span><button onClick={() => setMessage('')} aria-label="안내 닫기">×</button></div>}
      <section className="w-section" id="designs"><div className="w-section-heading"><div><span className="w-eyebrow">CHOOSE YOUR MOOD</span><h2>우리의 취향을 닮은 초대장</h2></div><p>세 가지 분위기, 하나뿐인 우리의 이야기.</p></div><div className="w-designs">{themes.map((theme,index) => <article key={theme.id} className={selectedTheme === theme.id ? 'selected' : ''}><button className={'w-design-preview theme-' + theme.id} onClick={() => { setSelectedTheme(theme.id); }} aria-label={theme.name + ' 미리보기'} aria-pressed={selectedTheme === theme.id}><span>WE ARE GETTING MARRIED</span><Botanical/><strong>서연 <i>&</i> 도윤</strong><small>2027. 05. 22</small></button><div className="w-design-meta"><span>0{index+1}</span><div><h3>{theme.name}</h3><p>{theme.description}</p></div><button aria-label={theme.name + ' 제작하기'} onClick={() => create(theme.id)}>↗</button></div></article>)}</div><div className="w-theme-info">선택한 디자인: {themes.find(theme => theme.id === selectedTheme)?.name}<button onClick={() => create()}>이 디자인으로 만들기 →</button></div></section>
      <section className="w-how" id="how"><span className="w-eyebrow">SIMPLE, PERSONAL, BEAUTIFUL</span><h2>마음을 전하는 일은<br/>어렵지 않아야 하니까.</h2><div>{[['01','월간 구독 시작하기','GitHub 또는 Google 계정으로 로그인한 뒤 월간 구독을 시작하세요.'],['02','두 사람의 이야기 담기','이름, 예식 정보와 사진을 넣고 미리보기로 확인하세요.'],['03','소중한 분들에게 전하기','공개한 청첩장 링크를 복사해 하객에게 전하세요.']].map(([number,title,copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="w-membership" id="membership"><div><span className="w-eyebrow">MONTHLY SUBSCRIPTION</span><h2>월간 구독으로<br/>우리의 초대장을.</h2><p>청첩장 제작 이용권은 토스페이먼츠를 통한 월간 자동결제입니다.<br/>구독 기간 동안 청첩장을 만들고 수정할 수 있습니다.</p><small>매월 등록한 카드로 자동 결제됩니다. 해지하면 다음 결제가 중단됩니다.<br/>해지 후에도 결제한 기간까지 이용할 수 있습니다.</small></div><div className="w-member-card"><span className="w-eyebrow">MONTHLY PLAN</span><h3>{member.active ? '구독 이용 중입니다.' : '우리만의 초대장을 시작하세요.'}</h3><ul><li>세 가지 청첩장 디자인</li><li>웨딩 사진과 초대 문구</li><li>실시간 미리보기와 공유 링크</li><li>구독 기간 동안 제작 및 수정</li></ul>{!user ? login : <>{member.active ? <button className="w-button dark" onClick={() => create()}>청첩장 만들기 ↗</button> : <button className="w-button dark" disabled={busy || !member.configured} onClick={() => void perform(startPayment)}>{member.configured ? '월간 구독 · ₩' + member.amount.toLocaleString('ko-KR') + ' / 월 ↗' : '결제 서비스 준비 중'}</button>}<div className="w-billing-actions">{member.renewsAt && <span>{member.cancelled ? "이용 종료" : "다음 결제"}: {new Date(member.renewsAt).toLocaleDateString("ko-KR")}</span>}{member.subscribed && !member.cancelled && <button disabled={busy} onClick={() => { if(confirm("다음 자동결제를 해지할까요?")) void perform(async () => { await api("/api/payments/cancel"); await refresh(); setMessage("다음 결제가 해지되었습니다. 남은 기간은 계속 이용할 수 있습니다."); }); }}>구독 해지</button>}<button disabled={busy} onClick={() => void perform(async () => { const state = await refresh(); setMessage(state?.active ? '활성 구독이 확인되었습니다.' : '활성 구독이 없습니다. 결제한 계정인지 확인해 주세요.'); })}>구독 상태 새로고침</button></div></>}</div></section>

      {user && <section className="w-section" id="my-invitations"><div className="w-section-heading"><h2>내 청첩장</h2><button className="w-button" onClick={() => create()}>＋ 새 청첩장</button></div>{!items.length ? <p className="w-empty">아직 만든 청첩장이 없습니다. 두 분의 첫 초대를 시작해 보세요.</p> : <div className="w-my-list">{items.map(item => <article key={item.id}><span>{item.published ? '공개 중' : '비공개 초안'}</span><h3>{item.firstName} & {item.secondName}</h3><p>{item.date} · {item.venue}</p><div><button disabled={!member.active} onClick={() => { setDraft(item); setTimeout(() => document.querySelector('#editor')?.scrollIntoView({ behavior: 'smooth' }),0); }}>수정</button>{item.published && <><a href={'/i/' + item.id} target="_blank" rel="noreferrer">청첩장 보기 ↗</a><button onClick={() => void perform(async () => { await navigator.clipboard.writeText(window.location.origin + '/i/' + item.id); setMessage('공유 링크를 복사했습니다.'); })}>링크 복사</button></>}<button disabled={busy} onClick={() => { if (confirm('청첩장을 삭제할까요? 공유 링크도 더 이상 열리지 않습니다.')) void perform(async () => { await api('/api/invitations/' + item.id, 'DELETE'); setItems(items.filter(value => value.id !== item.id)); if (draft?.id === item.id) setDraft(null); router.refresh(); }); }}>삭제</button></div></article>)}</div>}</section>}
      {draft && member.active && <section className="w-section w-editor" id="editor"><div><span className="w-eyebrow">MAKE IT YOURS</span><h2>두 사람의 이야기를 들려주세요.</h2><form onSubmit={e => { e.preventDefault(); void perform(async () => { const item = await api('/api/invitations' + (draft.id ? '/' + draft.id : ''), draft.id ? 'PATCH' : 'POST', draft); setItems([item, ...items.filter(value => value.id !== item.id)]); setDraft(item); setMessage(item.published ? '청첩장을 공개했습니다. 내 청첩장에서 링크를 복사하세요.' : '비공개 초안을 저장했습니다.'); router.refresh(); }); }}><div className="w-form-row">{(['firstName','secondName'] as const).map((key,i) => <label key={key}>{i === 0 ? '첫 번째 이름' : '두 번째 이름'}<input required maxLength={40} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/></label>)}</div><div className="w-form-row"><label>예식 날짜<input type="date" required value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value })}/></label><label>예식 시간 · 한국 시간<input type="time" required value={draft.time} onChange={e => setDraft({ ...draft, time: e.target.value })}/></label></div>{(['venue','address'] as const).map(key => <label key={key}>{key === 'venue' ? '예식장 · 홀 이름' : '예식장 주소'}<input required maxLength={key === 'venue' ? 120 : 250} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/></label>)}<label>초대 문구<textarea required maxLength={3000} rows={6} value={draft.message} onChange={e => setDraft({ ...draft, message: e.target.value })}/></label><label>교통 · 주차 안내<textarea maxLength={2000} rows={3} value={draft.directions} onChange={e => setDraft({ ...draft, directions: e.target.value })}/></label><label>디자인<select value={draft.theme} onChange={e => setDraft({ ...draft, theme: e.target.value as Invitation['theme'] })}>{themes.map(theme => <option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label><ImageEditor images={draft.images} onChange={images => setDraft({ ...draft, images })}/><label className="w-publish"><input type="checkbox" checked={draft.published} onChange={e => setDraft({ ...draft, published: e.target.checked })}/>공유 링크 공개 — 링크를 받은 누구나 볼 수 있습니다.</label><div className="w-editor-actions"><button className="w-button dark" disabled={busy}>{busy ? '저장 중…' : draft.published ? '저장하고 공개하기' : '비공개 초안 저장'}</button><button type="button" onClick={() => { if (confirm('편집을 닫을까요? 저장하지 않은 내용은 사라집니다.')) setDraft(null); }}>편집 닫기</button></div></form></div><aside className="w-preview"><span className="w-eyebrow">LIVE PREVIEW</span><InvitationView item={draft}/></aside></section>}
    </main><footer className="w-footer"><a className="w-brand" href="/">우리의 날<span>OUR DAY</span></a><p>두 사람의 시작을, 가장 우리답게.</p><span>Made for your once-in-a-lifetime day.</span></footer>
  </>;
}
