import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile, unlink, mkdir } from 'node:fs/promises';
import { recordStore, decodeRecord } from '../lib/binary-records.mjs';
import sharp from 'sharp';
const origin = 'http://127.0.0.1:3100';
const directory = new URL('../data/local-tests/components/', import.meta.url);
const records = recordStore(directory.pathname.replace(/^\/(.:)/, '$1'));
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const cleanup = []; let item;
try {
  const page = await browser.newPage({ viewport: { width: 1084, height: 834 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(origin);
  await page.getByRole('complementary', { name: '로컬 테스트 도구' }).waitFor();
  await page.getByRole('button', { name: '판매자 테스트 로그인', exact: true }).click();
  await page.locator('.user-name').filter({ hasText: 'local-seller' }).waitFor();
  await page.getByRole('button', { name: '＋ 프롬프트 올리기', exact: true }).click();
  const title = 'Review image test ' + randomUUID();
  await page.locator('[name=title]').fill(title);
  await page.locator('[name=summary]').fill('설명 이미지와 구매자 리뷰 테스트');
  await page.locator('[name=prompt]').fill('PRIVATE PROMPT ' + title);
  await page.locator('[name=instructions]').fill('한글 사용 설명');
  const png = await sharp({ create: { width: 80, height: 60, channels: 3, background: '#8061b5' } }).png().toBuffer();
  await page.getByLabel('설명 이미지 첨부').setInputFiles({ name: 'sample.png', mimeType: 'image/png', buffer: png });
  await page.getByLabel('이미지 1 설명').fill('결과 예시');
  await page.locator('[name=license]').check();
  const created = page.waitForResponse(r => r.url() === origin + '/api/prompts' && r.request().method() === 'POST');
  await page.getByRole('button', { name: '프롬프트 등록하기 ↗' }).click();
  const response = await created; assert.equal(response.status(), 201); item = await response.json();
  cleanup.push(item.id, 'review-' + item.id + '-900000002', 'report-' + item.id + '-900000002-900000001');
  assert.equal(item.images.length, 1); assert.match(item.images[0].src, /^data:image\/webp;base64,/);
  const stored = await readFile(new URL(item.id + '.bin', directory));
  assert.equal(decodeRecord(stored).images[0].caption, '결과 예시'); assert.equal(stored.includes(Buffer.from(item.prompt)), false);
  const ownReview = await page.request.post(origin + '/api/prompts/' + item.id + '/reviews', { headers: { origin }, data: { rating: 5, body: '본인 리뷰' } }); assert.equal(ownReview.status(), 403);
  await page.getByRole('button', { name: title, exact: true }).click();
  await page.getByRole('img', { name: '결과 예시', exact: true }).waitFor();
  await page.getByRole('button', { name: '설명 · 이미지 수정' }).click();
  await page.getByLabel('이미지 1 설명').fill('수정된 예시');
  await page.getByRole('button', { name: '설명 저장', exact: true }).click();
  await page.getByRole('img', { name: '수정된 예시', exact: true }).waitFor();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '구매자 테스트 로그인', exact: true }).click();
  await page.locator('.user-name').filter({ hasText: 'local-buyer' }).waitFor();
  assert.equal((await page.request.post(origin + '/api/prompts/' + item.id + '/reviews', { headers: { origin }, data: { rating: 5, body: '미구매 리뷰' } })).status(), 403);
  assert.equal((await page.request.patch(origin + '/api/prompts/' + item.id + '/description', { headers: { origin }, data: { instructions: '변조', images: [] } })).status(), 403);
  const purchaseId = 'purchase-cs_test_reviews_' + randomUUID(); cleanup.push(purchaseId);
  await records.write(purchaseId, { id: purchaseId, stripeSessionId: purchaseId, promptId: item.id, buyerId: 900000002, amountCents: 0, currency: 'usd', createdAt: new Date().toISOString() });
  await page.reload();
  await page.getByRole('button', { name: title, exact: true }).click();
  await page.getByRole('button', { name: '리뷰 · 별점', exact: true }).click();
  await page.getByLabel('사용 후기').fill('설명이 친절해서 활용하기 좋았습니다.');
  await page.getByRole('radio', { name: '4 ★', exact: true }).check();
  await page.getByRole('button', { name: '리뷰 등록하기' }).click();
  await page.getByText('리뷰를 저장했습니다.', { exact: true }).waitFor();
  await page.getByRole('radio', { name: '5 ★', exact: true }).check();
  await page.getByRole('button', { name: '리뷰 수정하기' }).click();
  await page.locator('[aria-label="평균 별점 5.0점"]').waitFor();
  const reviews = await (await page.request.get(origin + '/api/prompts/' + item.id + '/reviews')).json(); assert.equal(reviews.reviews.length, 1); assert.equal(reviews.reviews[0].rating, 5);
  assert.equal((await page.request.post(origin + '/api/prompts/' + item.id + '/reviews', { headers: { origin }, data: { rating: 6, body: 'invalid' } })).status(), 400);
  assert.equal((await page.request.post(origin + '/api/prompts/' + item.id + '/reviews', { headers: { origin: 'https://invalid.example' }, data: { rating: 4, body: 'invalid' } })).status(), 403);
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '판매자 테스트 로그인', exact: true }).click();
  await page.locator('.user-name').filter({ hasText: 'local-seller' }).waitFor();
  await page.getByRole('button', { name: title, exact: true }).click();
  await page.getByRole('button', { name: '리뷰 · 별점', exact: true }).click();
  await page.getByRole('button', { name: '리뷰 신고', exact: true }).click();
  await page.getByLabel('신고 사유').selectOption('기타');
  await page.getByLabel('상세 내용').fill('신고 기능 검증용');
  await page.getByRole('button', { name: '신고 접수', exact: true }).click();
  await page.getByText('신고가 접수되었습니다. 검토 전까지 리뷰는 유지됩니다.', { exact: true }).waitFor();
  assert.equal((await records.read('report-' + item.id + '-900000002-900000001')).status, 'pending');
  assert.equal((await page.request.post(origin + '/api/reviews/' + item.id + '-900000002/report', { headers: { origin }, data: { reason: '기타', detail: '중복' } })).status(), 409);
  const forged = await page.request.patch(origin + '/api/prompts/' + item.id + '/description', { headers: { origin }, data: { instructions: 'test', images: [{ src: 'data:image/png;base64,' + Buffer.from('<svg onload=alert(1)>').toString('base64'), caption: '' }] } }); assert.equal(forged.status(), 400);
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/reviews-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/reviews-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  console.log('PASS: image upload/edit/binary storage, purchase verification, review create/edit/rating, reports/duplicate prevention, invalid images, CSRF, mobile layout.');
} finally {
  await browser.close();
  for (const name of cleanup) await unlink(new URL(name + '.bin', directory)).catch(error => { if (error.code !== 'ENOENT') throw error; });
}
