import { chromium } from '@playwright/test';
import { createHmac, randomBytes } from 'node:crypto';
import { spawn } from 'node:child_process';
import { readFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const origin='http://localhost:3011';
const secret=randomBytes(32).toString('hex');
const directory=path.resolve('.next/upload-test-'+randomBytes(5).toString('hex'));
const child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--port','3011'],{windowsHide:true,stdio:'pipe',env:{...process.env,APP_URL:origin,GITHUB_CLIENT_ID:'test-only',GITHUB_CLIENT_SECRET:'test-only',SESSION_SECRET:secret,DATA_DIR:directory}});
let logs='';child.stdout.on('data',x=>logs+=x);child.stderr.on('data',x=>logs+=x);
const browser=await chromium.launch({channel:'msedge',headless:true});
let savedId;
try {
 for(let i=0;i<80;i++){try{if((await fetch(origin)).ok)break;}catch{} await new Promise(r=>setTimeout(r,250));}
 const page=await browser.newPage();
 const data=Buffer.from(JSON.stringify({id:42,login:'integration-tester',exp:Date.now()+60000})).toString('base64url');
 const token=data+'.'+createHmac('sha256',secret).update(data).digest('base64url');
 await page.context().addCookies([{name:'ac_session',value:token,url:origin,httpOnly:true,sameSite:'Lax'}]);
 await page.goto(origin);
 await page.getByRole('button',{name:'컴포넌트 올리기',exact:true}).click();
 await page.getByPlaceholder('예: 부드럽게 눌리는 버튼').fill('Integration test button');
 await page.getByRole('checkbox').check();
 const response=page.waitForResponse(r=>r.url().endsWith('/api/components')&&r.request().method()==='POST');
 await page.locator('.submit-upload').click();
 const created=await response;assert.equal(created.status(),201);
 const item=await created.json();savedId=item.id;assert.equal(item.author,'integration-tester');
 const persisted=JSON.parse(await readFile(path.join(directory,item.id+'.json'),'utf8'));
 assert.equal(persisted.title,'Integration test button');
 await page.reload();
 await page.getByRole('button',{name:'내 컴포넌트',exact:false}).click();
 assert.equal(await page.locator('.component-card').count(),1);
 await page.getByRole('button',{name:'Integration test button',exact:true}).click();
 const downloadEvent=page.waitForEvent('download');
 await page.locator('.download-actions').getByRole('button',{name:'CSS',exact:true}).click();
 const download=await downloadEvent;assert.equal(download.suggestedFilename(),item.id+'.css');
 await page.keyboard.press('Escape');
 const invalid=await page.request.post(origin+'/api/components',{headers:{origin},data:{title:'',category:'nope',html:'',css:''}});
 assert.equal(invalid.status(),400);
 const oversized=await page.request.post(origin+'/api/components',{headers:{origin},data:{title:'large',category:'버튼',html:'x'.repeat(151000),css:'a{}'}});
 assert.equal(oversized.status(),413);
 const oauth=await page.request.get(origin+'/api/auth/github',{maxRedirects:0});
 assert.equal(oauth.status(),307);
 const redirect=new URL(oauth.headers().location);assert.equal(redirect.hostname,'github.com');
 assert.equal(redirect.searchParams.get('redirect_uri'),origin+'/auth');
 assert.ok(redirect.searchParams.get('state'));assert.equal(redirect.searchParams.get('code_challenge_method'),'S256');
 const callback=await page.request.get(origin+'/auth?code=bad&state=wrong',{maxRedirects:0});
 assert.equal(callback.status(),307);
 assert.ok(callback.headers().location.endsWith('/?auth=error'));
 await page.getByRole('button',{name:'로그아웃',exact:true}).click();
 await page.getByRole('button',{name:'GitHub 로그인',exact:true}).waitFor();
 const unauthorized=await page.request.post(origin+'/api/components',{headers:{origin},data:{}});
 assert.equal(unauthorized.status(),401);
 console.log('PASS: authenticated upload UI, persistent file, reload and ownership, CSS download, invalid/oversized input, OAuth state/PKCE redirect, callback state rejection, logout.');
} catch(error){console.error(logs);throw error;} finally {await browser.close();child.kill();if(savedId)await unlink(path.join(directory,savedId+'.json'));}
